hash-format = "sha256"

[[files]]
file = "mods/aces-spell-utils.pw.toml"
hash = "fb660a11b66564299ce72d4926be5cdd42b38298c3f68200db52da1e881656d7"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4ca8b963965342aafdfe251e5306259eb9cf459d43e46d9695974dcff01465aa"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "81e399350b1510d2c9dc82c0fdec1fe6a7b6b0bd69ad9ca6ffc139f6232ff21e"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "0a349a3234c5ca3512e480cf8d9af33c00dac7170202c6b058019ffe34768742"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
hash = "105896bd81709c51629f3950e53c41765bc413f6d44edef7e776db8eb8e544b2"
metafile = true

[[files]]
file = "mods/cataclysm-spellbooks.pw.toml"
hash = "91ee26814273ff3f2527f9a793cf29d3d18f31e1042d3a6703c4a888b919bcfe"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "893fdff8f8874afad2fbf8ca68818cf3105759ff4286d01bcfb0cf2451b21061"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "a7b648a5867ea10a41e0e93b365ef7b2d1de5e823237d381cf823157c1c94b4a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "22286fa216349c0767808903a0a38662857d2adee54950a18cbf26c167a06029"
metafile = true

[[files]]
file = "mods/construction-sticks.pw.toml"
hash = "09fb23f1fd6c78f64eefa2d2775e3e5418ff48831e73568f71083cbe5c2b6464"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "42ffb6f5835250003da6ca3667ff751709ea295faee43b49c365b0f6c1e8f4d8"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "b65ee01fec17228645121952de6dec75053b0b4c59a8c8036d6fa7829819f3f9"
metafile = true

[[files]]
file = "mods/create-occult-engineering.pw.toml"
hash = "22434a6616f948f359f56c4ec6d3cc94b511b16dd0edd6484cb0c0adaf20df45"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "eb7b4a7b28d4806c7bb7a0cf84f4dca90fc5d62317573e9100542bc484a48750"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "fcffeffc0b8f4fb24c213e7d69449fca45ef80c8ed618409996e5b2f0f751d2c"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "f7d8ceefd80fb9efe9b555567d30defbdc05539e302c6d48b2904e078484d559"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/darksmelting.pw.toml"
hash = "6fc1a7cc83770a95f325579fb9c9e8962b2c7253369274ef3d64f5a130e9c035"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "a0703057f7a334e55a52a7913a001d1896c64f43ec1f8e758e0a50a9a2d23d66"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "1fc8ab07ea6f6abf5252a680f4ee72d7feaa652bc6b17214b1ddc5f5fe4c5d6d"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "840b796a400209ae1a80994a77ec67b8bcabe6d1f5ba96d4e066cce6bebc68c4"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "35bad9f01671b5b4284ad547dab6635b2a029980c88d82007690e9232a5cb420"
metafile = true

[[files]]
file = "mods/fancy-toasts.pw.toml"
hash = "3d986266a6f1f884d3786a2354b3458c9999728001e1961da63f31bdede735d8"
metafile = true

[[files]]
file = "mods/fdlib.pw.toml"
hash = "401dfbebe6c977ae47113f74f40d18e4439cc691749379c61f3514e2c42896cc"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c595b64a055d987de9d4ce6156c88eec58cf1b1ade849ff11731307f64a60941"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "402ca5410076adcf4bff4211d5d734572e0549955d3613ea0942309ec29a409b"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "d573695d37296209dc06495d359c4b283ffa6640bcfe8aa9c9b59eb420891788"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "6c275f621e7c3895ed34ee0e5bf847916a4285ac0f6452982ad6dccd5dd59851"
metafile = true

[[files]]
file = "mods/irisshaders.pw.toml"
hash = "4492da3ceac364a5bab62cb4cf585a91f3b9a840c8f5f4fafb6cfb85a14a41f9"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "c7104af995b95c68c28b8425e8a2da698f11500edc4e69056478090982d28915"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "6b3f722168fa57e23fca5441d9b74a11194d9252625d6bf0898c4d212f99380a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7fbe3225c134e823a07f3aecedace39fe866f327671ecca928f134399b94008d"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "395ed890024bdb90e7c0fed1edf8b3905a367942ded954fca92384c76a7e5601"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "62f78f4c3c3fac7e5f0507e2b7a2fdf854a263d34b45c0295df8a07255c37ead"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3d5d4c97ece8d1470d785fbffb44c1f17ca406931d08dd0cfd5d77745a956979"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3ac8c76f4cb2f1200d60fa2e74108d9cb9355346ddb8a4a735134dfac7b77136"
metafile = true

[[files]]
file = "mods/loot-integrations-cataclysm.pw.toml"
hash = "dc58aac183642c965c2b2fe267fb9f4635988a45ae3a64e73061af7814f3e4a3"
metafile = true

[[files]]
file = "mods/loot-integrations.pw.toml"
hash = "543b8a8ff5796648146f3102dea686e806f793052d329d0fa3efee8194d4df52"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "76eb9bf27dfc86977a8c46d0c1752b39b4dea19c827c0d68faf0c28bed0768eb"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
hash = "70db2eec093dadc990fe5862f9c3fe59a0d0de53542872eaccb5dc7f54be5fb1"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "27f11f64ea613816bf58ac8f661bdea47402edf6e0060c8137b38b4b32dfcb9f"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "b32898393c0ed300927b98e14c12a29d4334ac9e5395a73884202218a772f281"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "057044d2179d9e10b616ef8fa4cc870ad350842fc5c325ce0b3766160852cd13"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "b5be9033308bb88924ddbc0eb95011a6ad1674099f0db976ab5e05a28afc4971"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "26aca541ff9f149ef8bfdf69efb258d23339affd9fba4612bddd01e759fb0ffd"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
hash = "02c4f941c76c49cbaeb17e549dc0e37562ff5cbd6ca51fec9d8da3bb73538507"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
hash = "6139320e88063b06752654c37642e9a5102ed5e811a98fae639a2b7842d113dd"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "32f8d722b8e90a4ded120d3cbc7d6718d7bc2ea57a292af725978117710a6490"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "5b30dafc9e96471978376ee010cec0ddf592377ac94192c9370cb37973e1e95f"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "eab2f56ff9135b3b7253ea5a73deae2f887e2876f5f0432936044a6e926937b4"
metafile = true

[[files]]
file = "mods/qliphoth-awakening.pw.toml"
hash = "10980ab095279d494670724442a659fd3cc9fab5f67270fd2c9318326799ebb1"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "e5a88eeea38105e024dc8c8849e28d90af25cec68f1d0f6716796fe9746bddd2"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "aa83553db30adc47f86010f6443340251323a62ee3f9415a0c4332cb6d502419"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "75ff68dd0bfb30f2ff97f170ffbb74d5b6aaa791416c4a0559d09ac8778561ba"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "5d1a0fefc09545d23a75f37a7cd8b7dcf817a7a57fe28f1419b19be92476dcaa"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "8a0271e7d5c8f4badd2886fd9a8ca75c5a33868ac90828cf3b5dbe932025a0fa"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "6c0fac550bb053ee2728144a28819835823dcc6d04ad7897750431fe55100e53"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "ced1905adab298bd344b2cb44f0032b06a342933cbedfefba0d79bdd154954f5"
metafile = true

[[files]]
file = "mods/showcase-item.pw.toml"
hash = "02b3e986422df0ae3ee769ae445ddb1faa53e4314228f6af2eba34fc1fea07ff"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "1a610a4a75169fbebeece88a8e611fa0ad432b8661754a519166b23a6d643e36"
metafile = true

[[files]]
file = "mods/snad.pw.toml"
hash = "00ef477d75d3fc3fe9891e15a4bf429fe98101284853111b2fe19b5bb6e1a184"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "40e1fdc8c58f72bb947b978a773cf963b2d28bb49832500c2bd886f7ac6629bb"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f3c75c6d415e4d68307d972ed30ced99ba05968c7ff85301154a60fc42eeed95"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "c966ea02eb59f31dcaeaebe9d96c9b232a2fb16d2fe971729350e567a4ff1bd7"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "08ae2f34e6c0c1e27717ae13cbffe3e0f8efb1dd6b7480abf8cd75f87bde145c"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "6d755450264fa4a2afcaea38daa7be2a3f2fb3d0edad588ba7ed0cb4228b0f08"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "a2bb36d782a9babcf72faa8e3ccd5bb9a6e252eedab8bea698b1af34fa2fe552"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "d2c42f16fdb32a2b7a2cd8b976ef4d634176d1d25af2b72bae672067083ffdf5"
metafile = true

[[files]]
file = "mods/thaumon.pw.toml"
hash = "d8e6d54237412c135080aebf255787054523c962a154fce1afa8fc3fbb2adfc2"
metafile = true

[[files]]
file = "mods/tooltip-overhaul.pw.toml"
hash = "4d491c20c640428aad528c155e73a29e488f59fed9237d9df6b7f96a4305103f"
metafile = true

[[files]]
file = "mods/useful-slime.pw.toml"
hash = "77fdfc9985de9d35dbe2b049ee24ec49f408d64c8c4b1cbf51e37aaaa18cd20f"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "76b07f47147fb18bb31d8719f9c7beb6622b55f59ae14411c7cf022b4d99d910"
metafile = true

[[files]]
file = "mods/yungs-api-neoforge.pw.toml"
hash = "80f8b077b7fc1adfd2f895d79d004e09099b6ed5eaf9e8b0c7cd42759d8c18dd"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "4b9721bb5cba2f30464f1c406b7f6c6d65aad732b5d0091a4d22a4738fdc55c1"
metafile = true
