hash-format = "sha256"

[[files]]
file = "config/emi.css"
hash = "ab4344c331e2426edb5c657a45b004350d1e81dfdb32e13fc0648dd31521fd4a"

[[files]]
file = "config/tanshugetrees/config.txt"
hash = "fc34529b407997ae5ddd1cf1bfa7b0ff6471145066eee55ce25406dd2224a613"

[[files]]
file = "config/tanshugetrees/config_worldgen.txt"
hash = "1121c017eb56c265a879462486631486020cb3af9c4436aa8e2c165f1081ebfe"

[[files]]
file = "kubejs/config/client.properties"
hash = "344dd132ed81ceff5d5a203ddfbb79e1871d16ec71cb5b63377004730ba1aca4"

[[files]]
file = "kubejs/config/common.properties"
hash = "b489db7a4131d93e65352530d95c6244d8ad7305fd6a12fee8dc946fe4bda1d1"

[[files]]
file = "mods/aether.pw.toml"
hash = "6f87edf40bf0be7e7e266f9e2ff0bf7584c6bedff7975bad3259a21a60d1e598"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "11c40209898628cc8ca75d28f539c449384b40600bfc88272306f6138f4e4428"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "a966c425617e0583ccadc2fe7f521a53833c93f4aacd9c89c24ad7cc76eca97a"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "8d0321177fed4a0b48554c40158b43db62f6cdaa768f584ef6a11575dfaa6223"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "caf733526eccac9b26d70b2649d5fa99d832d16a2379a9aa2515049c77765077"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5e9edd1fd2395f14a0c8a4acbdbdd61e1047be1f0033deb3140d2ce0d093e9d8"
metafile = true

[[files]]
file = "mods/azurelib.pw.toml"
hash = "698b75b7fef9f88a359459d953b7e4ed9f0ee8435ee69deace056b434da77d83"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/better-chunk-loading-forge-fabric.pw.toml"
hash = "7499dcfc1c246bf1ceb3b82992cc7478a9d8e29900f6c77c1c2a425665b4841d"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8341be7376192fe2cbffa3af36060ab8684adb2862efe478d697810cdd979e95"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
hash = "8c0f450f657efab9f25ae5bc6dfb6a43aafc0e7e411fea8df2c885593bb67fde"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "da069e723737ae49203f7572eb774be0fd21f5f083ce7a7ee1bed25916befca8"
metafile = true

[[files]]
file = "mods/callable-horses.pw.toml"
hash = "e87bc30ef60440cd3f9055490e9f707c0dd3287e6cd50edfb20c9594428cd0f4"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "14481081a9e233f4ba57df8a77ce028184818143eae1c73b60749ea482c912e9"
metafile = true

[[files]]
file = "mods/cataclysm-spellbooks.pw.toml"
hash = "a195ba4ca1c853665a0664e90a358ea2838fe2decc438181b90d9949081a2228"
metafile = true

[[files]]
file = "mods/celestisynth.pw.toml"
hash = "5b7e57aeb7b340d1d637d25504fd33cfc4db3909ac0cb9f20e5c117ba5f39fd5"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "2149c32394192bcb574d275628fef7dae5fb82ef6154ecbe134bcb5eddf31a78"
metafile = true

[[files]]
file = "mods/clean-swing-through-grass.pw.toml"
hash = "47fb31c0dd8d57b949af33591d811bad064e29599d5753ea8a6011e0e1498d0c"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
hash = "8708549001bab45590a8560d7c0dd9b0859e416887f7b63b3edd2c09d05246e5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "96204145e12506e0625d8b9bfa05aad54e9a62fd511bae39f0d57fcb5e39f4cc"
metafile = true

[[files]]
file = "mods/colorful-hearts.pw.toml"
hash = "a24c070e0d9c218c4d286c10d6a77fb845708a1bbd13ca5aa882453674047cbd"
metafile = true

[[files]]
file = "mods/colorwheel-patcher.pw.toml"
hash = "483473569b2dd584b7536fec935a8f3c1ac008c5421f911d35f539de5b4d05f0"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "d13a6498818900343ba37abb336dbb03dc1b0cb487e3c4a02d9c74474bfdc81e"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "fdf6907c29fa9ded3d3ab3ce04853f59256978dbfefe6af8618c492677c875e2"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "5b0eaf19630d6145093ae6ff9a21cf2dbdd0da53d9289673ad5ccb099afa18b7"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "00bcb49250fa1f8e533a321cd650e8e57e3d7f7b6178e0f92c21b93736bfb6a8"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
hash = "cfa8aa9c0437721dab2057c932c9cf8ec3d3a11f672040601305238d13df85e8"
metafile = true

[[files]]
file = "mods/create-estrogen.pw.toml"
hash = "12eb225906d0765673672188489469155163bc9e289e8b442b04e2b5f5264370"
metafile = true

[[files]]
file = "mods/create-occult-engineering.pw.toml"
hash = "46d7500e48e9ec66f88351ef8503bb35ab5bfd71e9edca54e6a11186de3b8a34"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "44897cbb7686cb987f2fec98a87e698d78b104e3454d5d25eecba6876ef83055"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9d7971a7af2ff4a96a0e5aede76f9cf8dc978da601e2754f79d6ec8631125bb9"
metafile = true

[[files]]
file = "mods/critters-and-companions.pw.toml"
hash = "dce7de4e5a948da16df350f36ffdd1b0be9843041777b0b2e3e1e1e87e1b1c9d"
metafile = true

[[files]]
file = "mods/culllessleaves-reforged.pw.toml"
hash = "e38d187eefae043e892eb6ce932f5360718d02d71f9e8072e8ec38ec0667753b"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "2eb26b157c4159bfeff6a00147afa35284397d558f84b55367d1a41064d7456a"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "1315cd56b0b4a5b3d53374cebf4f1f3cd0546b05058740847bd226c1d1ccab39"
metafile = true

[[files]]
file = "mods/cynosure.pw.toml"
hash = "e5d3b81a1081f11f442bda74f344c0bcdd7c4c0f3eb3768598659903f4856eb2"
metafile = true

[[files]]
file = "mods/darksmelting.pw.toml"
hash = "303d9818e8c8a9568c3dbb354c71c92fdf8b0e85a5ebd2e2b9fe3dd6c75e38cd"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
hash = "acb7ebe72eeb476a26e5777cbbbad0a270db8ff85de0aa417be8e1228d26e2f4"
metafile = true

[[files]]
file = "mods/deep-aether.pw.toml"
hash = "90484736d203b7fcc858d6f87425bd333326311aa593c75cc53ffb09529d7472"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
hash = "8f2270a50a633db681826cbfb691e6efdb25e1e0c4702125c13d525b52fe229f"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "a1575677daaaf6ea6dac12e5a10073e34025e5ca2c35b6d36ad4a5a0edbc0e82"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d48a1ea93de8cd5febb95ba52989d8d9ab4e998cfbdf9c1076a9f2e571d2fcbe"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "35ef939dd24fc39919a5a50c86e28468e1b3a178cdf61e8197dad72601f25ba5"
metafile = true

[[files]]
file = "mods/entris.pw.toml"
hash = "7d60bfc6994036071466b08b1b557a79d8f11544ee88af28166997dbf3a63f81"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "c006d771188a35a178b4831098e661ed2fdb9576fc2fce23544b874b5263f640"
metafile = true

[[files]]
file = "mods/expandability.pw.toml"
hash = "a9c35b5265445218f14be7bce6c01bcaf7f6c3e456e8ef675ae41b3d0298e3a5"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "0ba2a01934d2de588071ac5a5281dd9a29fc46166fe6b9f99a809a70fe1a6668"
metafile = true

[[files]]
file = "mods/fancy-toasts.pw.toml"
hash = "217612c305c4a3d770dec753455d28784e127b2ee2f9527e478c9d57503c0725"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
hash = "0b4c64ea1972059276a689110c83de55ca01f211320bb9f5c3bff360cf2c6f24"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "b4fc21a94115c0044b9c7bf79b5b5eddef5034361039a1cbc1af4afc47662f46"
metafile = true

[[files]]
file = "mods/fastsuite.pw.toml"
hash = "a828c60907bd972cb75263bce3bd6bacfb31b98ccb3d5556ad10c7be81258e5d"
metafile = true

[[files]]
file = "mods/fdlib.pw.toml"
hash = "a49050d49706c8f01cb003b47c0f2249ea002165eaf58597077165914d791672"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "5bd0506bc0be25116b234f2b5af9447f60d82ae1cb6c5be4e12d8841f6c2501c"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "62ef7e92478035b77e996189984e4749b2d876ed0a389977a2670a28f105bfd2"
metafile = true

[[files]]
file = "mods/formations-overworld.pw.toml"
hash = "d1b043070d2dcc46956e73e7b53f9fc62aa8d36dc6b340203dc825a3cec7ec35"
metafile = true

[[files]]
file = "mods/formations.pw.toml"
hash = "9ee68d3b3b1a727f1ed19a704fc137db3f825a989057c2d9a6ba95fda33f5f2b"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "48e2fa3089beed20a23ff2d171259768b2080ab0ff196841a18eb93c38e1c8b2"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "1c383e66311b5edd6d7116ae0544108d60450f58e94853126665d75d85561d68"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "b3fed05c5f1ab83304f54ad12e42e05e17b3aaf93da7370e94ace9eb863ae890"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "88f142bda6bfa6aff4f4d4e12b8ba7581aa40e3f163039a533f09dd6d634e093"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "84a9d82ec68d20fdbec18b4dd2735310e3301e841366d3caac95fe2666e46136"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "b9a7e71472f5f88229bf2f9e214b223b3900052bdc56075906d7a22acf74568c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "eb089373d47632a85bb7596b1143b719d7675f5e2782586aa0c340069d699700"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "9779719134e508c31ef0cb08ed272daef6d3b4a8a5bff07e48f9695e88e5a410"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "4dced2a3e682da6611b0d0929819f549486e8a277f58e495420056cf350319d2"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8f359d190506a6f824763b8e7c390d9e22204ef11e3ffa5ef980000d17e2c2b6"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "1678327ac50408273c1828b631929128d3fdfd54cda7b2e823ce9352495a68ff"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "873d23ad2ce05e3e92a05e011f3f9a375a745a4ca6ed4c9fffb0518fc8255bf7"
metafile = true

[[files]]
file = "mods/lendercataclysm.pw.toml"
hash = "75199fa3b762c5aa781e3cb2aab7779d19128b2a1c5b15798d5e613df8d16573"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "60af8798dbf3e300a5af44125595afcd5d1e70072448444156364f222cc03e98"
metafile = true

[[files]]
file = "mods/lodestone.pw.toml"
hash = "a484a0a768e886244dab01dd9793d979ca5d57b8327f9f4caa36a3031fc46d63"
metafile = true

[[files]]
file = "mods/loot-integrations-cataclysm.pw.toml"
hash = "dc58aac183642c965c2b2fe267fb9f4635988a45ae3a64e73061af7814f3e4a3"
metafile = true

[[files]]
file = "mods/loot-integrations.pw.toml"
hash = "41a036a86db9c0cab20b9b8956b0749bdfea13942d6ca00668304e5d0731166f"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "e8b4876d403b4f4daab64bad9704a5b271a33031d1ff8d19d23ebd1e3b8dd39a"
metafile = true

[[files]]
file = "mods/malum.pw.toml"
hash = "19821414a26c40c40f4584102cbc73df7282ef1aadf8f948b37f97c6f44a91a3"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
hash = "a433c965c277b4f3b89606b2e87c56545bca0c42568e5ee0e75962628ddd939e"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "893b3e91c2165e5b3d7950ad543d6898bd3d50b7bfa411352ab0c60447c9e8e3"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "5859dfd186c4ac5e7e4627639dc2aeca5478dd1f9d6f09020e49a9788edbf4de"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "11cd7da81a933aab04f091e2c25447b6d11ebe98bfeed244426a86dd31f3df04"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
hash = "81da708e6a9add4237562e15bd2be857cfa3908c50951408ab2137ff1c68fbbd"
metafile = true

[[files]]
file = "mods/nameless-trinkets.pw.toml"
hash = "200c786fa79062b05dee983ea88deb97d12a00e4de237fe85a35ab4e02b8cb5d"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "464e83a35e22e9bbdf7be38cf7a7a98c39462a0a50b01d2a1355bcae9167ea7a"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "e1b49409243ca8ccf9d1ef4d458dc1a887a19f9b18dcd5088d56c19073d57b43"
metafile = true

[[files]]
file = "mods/notenoughrecipebook.pw.toml"
hash = "5dd8e869fbebed8abe7886fd28f1f192c420d3fefd9f714939c2a501d3a4a1af"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "96008b869b133a400c97313afa460bda3b4d43aeddcafaf04c4141f9193f3095"
metafile = true

[[files]]
file = "mods/occultism.pw.toml"
hash = "5e223066775d04e26cb36e7b459581437e56bf97907d5034325a1a564be428fc"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "320c4d3a50b1f2f45d64d2f88c8c16473bc85b95d67e54ff93205ac9d2ead3cf"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "5ef885f9912ff6aa73db254b63a3cd22520f06261bc3c38e7c92f449806a9044"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "dec2bc011d4ca1d451aaa3eea477f13366bfb13beba0716018f47d9331a50d8e"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "b52622122c19a3894e62fc5506d7c3332d202504fd406d6718be646f979feb40"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "5ca42f4c23aee558ed76923d4fb92ecee736ebacb53790445c09d46bd9ccb27e"
metafile = true

[[files]]
file = "mods/qliphoth-awakening.pw.toml"
hash = "c32db52ce4113e936f1c34e1d28a0d518a1756d97042ff01ae7fa9fc8e694a00"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "4eb683644ee4e38e00b06df946b71ad8fedaa860fcabbd91ec6ceb71c65b8d81"
metafile = true

[[files]]
file = "mods/reliquary-reincarnations.pw.toml"
hash = "47488a6562c760f1964eabb1a3ad962592c29ef2e193f1557c0eded583790e72"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "e242387207a2538b5ccb55697174c65e549e1eb2fef9da37e1ad3734e0372b65"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "ef0264b7d819848f72ab2f34643306187e712965a8246e1f733e1bd39d8fd681"
metafile = true

[[files]]
file = "mods/resourcify.pw.toml"
hash = "13b5eddbd1850ea7de12a83260b00f32d0644ac2483c2312b22ca310724488dd"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "ca4411ac6d8a9a892948bb63cd0ba52ae5523ca5e257632d6ae8c933b660c5ee"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "70acbe76903121faa88da57c77a8a1eada9c0e4b58143abb8ccd57b766b14148"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "b56161ba01e298c7a28a593dcadc2d1b802c49d7bbdc01d0c7d03a31e04b6408"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "8d3e9ef52ac3b65fb976629b55652ca30f9ad8b7ff37925c3111ae78386e1a97"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "5240c62752415b5d66d4beffec4fe98c253eba8ebcbb2a5c1097fc3ad3de0b00"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "0462f0b658c766e1ccb9974f576090713738606d6513aba89cf8d5ba2b00847b"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "93123611f5de9f6c8b25e1fe2e1b7defdcf65810fe3aeb9aa8800e8ecfafa6a3"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "6706d08c5acf29642c796b828dfa7de56e186ef6a45dd70374e07e284494cf8b"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "33b4d30364583bdd7cde0eb6dddd546abdbb4fc59697af3cf3b59a3beb8d0729"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "dff2df7c34cadde67c632ef4cf043468b8dbc9c2b53b735984dd7e45dda2cd8d"
metafile = true

[[files]]
file = "mods/starcatcher.pw.toml"
hash = "ba7bd81b4ddeda5d02873fe0f6d4bdaf37b9a663f8ed657a38bdfdf80097392c"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
hash = "17f162241760e4a26023aff789daa5455a8657e8e68d3bafe6aa19a7b46dd4f3"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
hash = "8f907c02b348e25358cf2bca42e9105b9b6103f670bf36432da6752e2c8806db"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "4b2933a18390fe4fc0efef26556413372a96a0f5ed639c713643ed8e49649c58"
metafile = true

[[files]]
file = "mods/subtle-effects.pw.toml"
hash = "61cb40e4df3b5b700e4b983204c761f7ca8dfc61309a53400aa60c6945c700fb"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "31883f2697767614c5b0671e9600c4e584c8e60be8062867667ddfc9d2624e23"
metafile = true

[[files]]
file = "mods/tans-huge-trees.pw.toml"
hash = "7138cd638d45d08bf1c961e0d247f11441f1df8c5065983b922542dadda32601"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "fde3d3b1607636100e382dce1bba80ab4608ebfa1ef888a37b86bc8c7dcbafe5"
metafile = true

[[files]]
file = "mods/thaumon.pw.toml"
hash = "4dcb6364eb099e043d81c42583cf9a8496a97ef32a235a204cf652aaf9e13631"
metafile = true

[[files]]
file = "mods/tooltip-overhaul.pw.toml"
hash = "1cacce9d22012caaa226a57b7c4c61ea539dd36142ea1862ac93bec1627bc135"
metafile = true

[[files]]
file = "mods/useful-slime.pw.toml"
hash = "24ddefc0a5d0e2fdbe82fa9abfc90de118edf3393c29c68806cb852c820fd61b"
metafile = true

[[files]]
file = "mods/via-romana.pw.toml"
hash = "7219a028e64d3407c23845431d40caa93b4d335656d4a7f4405fa4f2e19b4887"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "c1bf8d194ef2c39c6046fa53861571b7c569277923b35e6d95a58ee4644eedb6"
metafile = true

[[files]]
file = "mods/voidscape.pw.toml"
hash = "607057a50307a9da24c04f8371158698fa0a2d2770b9062035ed88228dc96224"
metafile = true

[[files]]
file = "mods/yeetusexperimentus.pw.toml"
hash = "7dbe376c64d52ddc3e52ca6ce6b07d8c5d76bf9ef68d58267bb9e9c6d8fb2c09"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "9fb6a1a06b18f2ce7b0811200339d997925cb39bde220fbaea4d5c8067376c12"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "58148fa22c72e0b0eac5e35fed0be9194ad59fe848298c1b61b565fa3158b2f4"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "31fca121c5b55c624ed203937c8f9b4d13cfe32f80bb85405aa4c65238378b15"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "24876f77eefbda53cbeb1b3261dadd63e37f46389d184380e1e3f1f04d1f93f3"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a5af976bf45b8e0aaaa22bebb11504ef0687e90d2cff9d3fa3b648c0757c1446"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f58f817a74f2b26fca9922263bf3f616deb0ee709212aa944ece857bf47a2d6e"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "a9421a7a29ac8ee6e0598ea20025ad2c30e6198b796324184600621743437c91"
metafile = true

[[files]]
file = "mods/zume.pw.toml"
hash = "72e1a205fcb059200604689d3a5765a2e314df5216d25b3e5cc48fe407df6356"
metafile = true
