name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99d8bcabc8fc93c08f2bb65437440a73c45f869c992be749d08fd2723c108ec3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
