name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dea300c6e81bcfe51d3429616f8389c0c244b62d372dbc95866f70c26eb1dec0"

[versions]
forge = "47-4.3"
minecraft = "1.20.1"
