name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78aed7499cc6830efe96203d51d366c4da87cf962b9c93b4c2765ee8b38222f0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
