name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d77567a81607eeeab08f25e6ea5288b14018ee3f7bd4c0d2af0951a856a3983b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
