name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65c01c8f3a1c66a9298342db17fcc61a3617ecb11debeb0e4fb7a14cfd060aef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
unsup = "1.2.0-pre4"
