name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc0696bfdce75ace8b657b94de008fb3e0c125d2252647bb769b43eae750aedb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
