name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34123a537d6be4cc26be8e40f27af07c594e69c24cc36a7ba23579ab9cf6285a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
