name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44503d7242c1332988a14f881e93f026709856cd83961afcd88d26988afc6b4c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
