name = "Silly Modpack"
author = "alyx"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a8f24825642d20111f43f171591bc503c410902c3e751eed8209e9d7600e6a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
