
#Client-side Visual Settings
[plants]
	#If true, Ghost Fern blocks emit ambient particles client-side. Default: true
	ghostFernEmitsParticles = true
	#If true, Celestial Blooms blocks emit ambient particles client-side. Default: true
	celestialBloomEmitsParticles = true

